### ISSUE TITLE
This version doesn't compiled

### ISSUE THREAD

**Issue by nadavrap** [DavidPowell/arcpubs#1]
The current version return an error. After executing pdflatex, getting the next error:

`(/usr/local/texlive/2016/texmf-dist/tex/generic/ulem/ulem.sty)`

`! Illegal parameter number in definition of \blx@defformat@d.`
`<to be read again>`
`4`
`l.15     {\textbf{\uline{\ifblank{#4`
`}{}{#4\space}#1}}}%
`
Can you please check that?

**Comment by DavidPowell** [comment]
I think this is a change in how the different parts of author names are referred to in recent versions of biblatex. I have just pushed a version with some changes I had to make after updating my MikTeX distribution. Hopefully it solves your problem.

**Comment by nadavrap** [comment]
It solved the errors.
