### ISSUE TITLE
All the numberings are set to [0] & dealing with accents in last name

### ISSUE THREAD

**Issue by Raphouu** [DavidPowell/arcpubs#2]
Hi there ! 
Thank you so much for generating a code that automatically generate a publication list in LaTeX with the last name highlighted. I haven't been using Latex for a while so I apologise if my questions are somewhat naive. 
I have managed to generate the list of publications but I have two problem : 
1) all numberings are set to 0 (I get the following error message : ! missing = inserted for \ifnum. <to be read again > A \show articles
2) my last name ends with é and the accent has been sometime forgotten so I was wondering whether I could add a second author name for which the name could be highlighted 
And two small details : can I add a small space between each publication & increase the margins ?
Thank you so much in advance,
Best wishes,
Raphaële

**Comment by DavidPowell** [comment]
I'm sorry, this code is no longer maintained. I found that updates to the dependent packages would continually break this code, for reasons that I do not understand.
